require:
  - ../lib/rubocop/cop/captive/active_admin/active_admin_addons_presence.rb
  - ../lib/rubocop/cop/captive/translation/devise_i18n_presence.rb
  - ../lib/rubocop/cop/captive/translation/rails_i18n_presence.rb
  - ../lib/rubocop/cop/captive/translation/kaminari_i18n_presence.rb
  - ../lib/rubocop/cop/captive/rspec/specify_before_parameter.rb
  - ../lib/rubocop/cop/captive/rspec/no_db_in_unit_specs.rb
  - ../lib/rubocop/cop/captive/rails/after_commit_not_allowed.rb
  - ../lib/rubocop/cop/captive/rails/force_ssl_enabled_in_production.rb
  - ../lib/rubocop/cop/captive/rails/migration_methods.rb
  - ../lib/rubocop/cop/captive/rails/no_disable_ddl_transaction.rb
  - ../lib/rubocop/cop/captive/rails/no_email_from_controller.rb
  - ../lib/rubocop/cop/captive/rails/no_float_price_columns.rb
  - ../lib/rubocop/cop/captive/rails/no_find_by_in_scope.rb
  - ../lib/rubocop/cop/captive/rails/no_has_many_attached.rb
  - ../lib/rubocop/cop/captive/string_where_in_scope.rb
  - ../lib/rubocop/cop/captive/no_app_env.rb

# ActiveAdmin
Captive/ActiveAdmin/ActiveAdminAddonsPresence:
  Description: 'The gem `activeadmin_addons` should be added to the Gemfile if `activeadmin` is present in Gemfile'
  Include:
    - 'Gemfile'

# Translation
Captive/Translation/DeviseI18nPresence:
  Description: 'The gem `devise-i18n` should be added to the Gemfile if `devise` is present in Gemfile'
  Include:
    - 'Gemfile'

Captive/Translation/RailsI18nPresence:
  Description: 'The gem `rails-i18n` should be added to the Gemfile if `rails` is present in Gemfile'
  Include:
    - 'Gemfile'

Captive/Translation/KaminariI18nPresence:
  Description: 'The gem `kaminari-i18n` should be added to the Gemfile if `kaminari` is present in Gemfile'
  Include:
    - 'Gemfile'

# RSpec
Captive/RSpec/SpecifyBeforeParameter:
  Description: 'Specify the parameter in `before` blocks. Example : before(:each) or before(:all)'
  Include:
    - 'spec/**/*'

Captive/RSpec/NoDbInUnitSpecs:
  Description: 'Do not hit the database in unit tests. Use `instance_double` or `Model.new` instead. If testing a scope, move to spec/integration.'
  Enabled: true
  Include:
    - 'spec/**/*'
  AllowedPaths:
    - 'spec/requests'
    - 'spec/system'
    - 'spec/features'
    - 'spec/integration'
    - 'spec/factories'
    - 'spec/services'
    - 'spec/jobs'
    - 'spec/support'

# Rails
Captive/Rails/AfterCommitNotAllowed:
  Description: "Interdit l'utilisation de `after_commit` dans les modèles Rails."
  Severity: error
  Enabled: true
  Include:
    - 'app/models/**/*.rb'
  Exclude: []
  Match: 'after_commit'

Captive/Rails/ForceSslEnabledInProduction:
  Description: "Ensures SSL is forced in production, so that secure cookies are used."
  Include:
    - 'config/environments/production.rb'

Captive/Rails/MigrationMethods:
  Description: "Avoid using ActiveRecord::Migration methods in `up` and `down` methods. Use `change` instead."
  Include:
    - 'db/migrate/**/*'

Captive/Rails/NoDisableDdlTransaction:
  Description: "Avoid using 'disable_ddl_transaction!' in migrations."
  Include:
    - 'db/migrate/**/*'

Captive/Rails/NoEmailFromController:
  Description: "Do not send emails from controllers. Because it doesn't follow the MVC standard"
  Include:
    - 'app/controllers/**/*'

Captive/Rails/NoFloatPriceColumns:
  Description: "Avoid using `float` type for price columns. Use `decimal, precision: 10, scale: 2` instead."
  Include:
    - 'db/migrate/**/*'

Captive/Rails/NoFindByInScope:
  Description: "Avoid using `find_by` in a scope. Use `where` to return a collection or define a class method if you need a single record."
  Include:
    - 'app/models/**/*'

Captive/Rails/NoHasManyAttached:
  Description: "N'utilisez pas `has_many_attached` (Active Storage). Préférez un modèle associé avec `has_one_attached` pour pouvoir ajouter des attributs (position, image de couverture, etc.)."
  Severity: error
  Include:
    - 'app/models/**/*'

# other
Captive/StringWhereInScope:
  Description: 'The `where` method should be used in a scope in a model.'
  Exclude:
    - 'app/models/**/*'

Captive/NoAppEnv:
  Description: "Do not use `APP_ENV` environment variable as it conflicts with standard Rails/Rack environment variable `RAILS_ENV`."
