inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Autoriser l'environnement staging (Rails.env.staging?) en plus de development, test, production
Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test
